### ISSUE TITLE
MSI has an invalid certificate

### ISSUE THREAD

**Issue by RichyA** [carstengehling/jirastopwatch#106]
The 2.2.0 MSI seems to be code-signed by Microsoft? Clearly that's not right, and causes Edge (and possibly other browsers) to warn users to delete the download as it looks invalid.

**Comment by carstengehling** [comment]
Sounds strange. The MSI is made with a Visual Studio Setup Project (.vdproj) with no particular settings. When I download the MSI from Chrome, I don't get this warning. I never use Edge, so I haven't experienced this.

However, if you are concerned about the validity, you can just download the source code and build it with Visual Studio 2017 Community Edition. :-)

**Comment by carstengehling** [comment]
I just tried to download from Edge, and I got this warning:

![image](https://user-images.githubusercontent.com/54675/33625601-5e3a5470-d9f8-11e7-9f51-cf96cfd7686e.png)

Apparently, it is Microsoft's own tools, that causes this problem: https://stackoverflow.com/questions/35391691/vs2015-installer-projects-adds-invalid-microsoft-signature-to-msis - rather annoying.

I will see at some later point in the future, if I can find another install tool to use - also since VDPROJ are no longer supported in VS 17.
