### ISSUE TITLE
Jira non-responsive

### ISSUE THREAD

**Issue by JonnyBart** [carstengehling/jirastopwatch#12]
Our Jira Cloud environment became unresponsive, which we reported to Atlassian Support. I have copied their response below, which appears to relate to API calls from Jira Stopwatch - the filters are those used by Stopwatch.

> JIRA went down due to out of memory issue and I suspect this caused by massively REST API calls to JIRA (see log below):
> 
>  258 /rest/api/2/search?jql=project%20=%20%22IT%20Service%20Desk%22%20AND%20resolution%20is%20EMPTY%20AND%20text%20~%20Failed%20AND%20text%20~%20Daily
>     240 /rest/api/2/search?jql=assignee%20=%20currentUser()%20AND%20resolution%20=%20Unresolved%20AND%20project%20=%20%22IT%20Service%20Desk%22%20ORDER%20BY%20updated%20DESC
>     233 /rest/api/2/search?jql=(assignee%20=%20currentUser()%20OR%20project%20=%20Administration)%20AND%20resolution%20=%20Unresolved%20ORDER%20BY%20issuekey
> 
> I would suggest firing this REST API call once at a time to avoid JIRA from going down again since it would take a lot of resources to return the results of this REST calls.

**Comment by carstengehling** [comment]
Ahhhh... Well this request is made once every 30 seconds, which I honestly did not think would be a problem. Of course if, say, 60 people are using StopWatch against the same server, that would result in the request being made twice every second - and only if distributed. More likely a lot of them would request at almost the same time.

I will change this, so that the items in the drop-down boxes (Filters + issues) are only updated on request - that is when you actually open one of the drop-down boxes.

Thanks for getting this to my attention. It was never my intention to create problems for other people with this. :-) My sincerest apologies to Atlassian - a fix will be out ASAP.

**Comment by carstengehling** [comment]
@JonnyBart I've made the changes described above and released a new version of StopWatch: https://github.com/carstengehling/jirastopwatch/releases/tag/1.6.1

Please update to this version along with your colleagues, and let me know if this helps.

**Comment by JonnyBart** [comment]
Thanks for that Carsten, we'll give it a try.

For your information, there are 4 of us using it.

**Comment by carstengehling** [comment]
Great - in any case this is really the right way to refresh the issue list. It also means, that if you create/assign a new issue, it will be available in the dropdown immediately when you open the combobox. Before you could be waiting up to 30 seconds. So this is a way better solution in many cases - thanks for spotting it.
