### ISSUE TITLE
feature request: edit comments without committing worklog

### ISSUE THREAD

**Issue by sahlex** [carstengehling/jirastopwatch#27]
Hi.

Many thanks for this great tool. It simplifies logging time for different tasks a lot.
However, sometimes it'd be helpful to add comments to one issue over day and submit the worklog in the evening, having the collected log attached.

Right currently you can add comments only when committing the worklog for one issue.

How do you think about it?

Regards,
Alexander

**Comment by carstengehling** [comment]
I'm not sure which version of Jira StopWatch that you are using, but since version 1.4.0, you have the option of saving your comment for later, just as you ask. See how below:

![image](https://cloud.githubusercontent.com/assets/54675/17021910/4f459bfc-4f4b-11e6-9ec7-2478acf4eeb8.png)

If you press "Save for later" instead of "Submit", the comment will be stored along with a timestamp. Your "Post worklog" icon will also get a red exclamation mark added, so that you know, that this item contains unsubmitted comments.

**Comment by sahlex** [comment]
Oh my!

This is exactly what I'm needin'. Many thanks.

**Comment by carstengehling** [comment]
You are very welcome :-)
