### ISSUE TITLE
Version upgrade should keep previous config

### ISSUE THREAD

**Issue by eviweb** [carstengehling/jirastopwatch#33]
Hi Carsten,

thanks for this very useful tool.
It would be great if after upgrading to the last version, previous settings could be kept.

Thanks

Eric

**Comment by carstengehling** [comment]
You are very welcome.

I agree - it annoys me as well. The thing is, that I use .NET's built-in Properties.Settings module to handle default and user-specific settings. And I also use Visual Studio Installer project extension to make the installer MSI. 

For some strange reason these two components don't play well together. So I'll probably have to run with my own user settings file instead. This means that next release will also have this annoying problem (because now it will be a completely new settings-system) but after that, subsequent releases should keep existing settings.

**Comment by carstengehling** [comment]
I found out, that the built-in ApplicationSettings have a nice way of fetching user's custom settings on upgrade: http://stackoverflow.com/questions/534261/how-do-you-keep-user-config-settings-across-different-assembly-versions-in-net

So this will now automatically work when next version of StopWatch is released.

**Comment by eviweb** [comment]
Hi @carstengehling,
thanks for the info and this enhancement.
Eric
