### ISSUE TITLE
Jira cloud new tempo 

### ISSUE THREAD

**Issue by GallonMael** [carstengehling/jirastopwatch#86]
Hi,

New tempo for Jira cloud broke Jira stopwatch :( Are you already aware of this issue ? 
You can basically push the time but it is not saved in the new tempo.

Cheers

**Comment by carstengehling** [comment]
No I was not aware of this, since we don't use Tempo in my company. I'm not quite sure, what exactly you mean by it "broke Jira StopWatch" - could you elaborate?

StopWatch saves time in Jira by adding worklogs - basically just by using this API call: https://docs.atlassian.com/jira/REST/cloud/#api/2/issue/{issueIdOrKey}/worklog-addWorklog

I'm not really sure, what Tempo is for, so you will have to be more specific about what your problems are.

**Comment by GallonMael** [comment]
Hi,

Well, on the jira cloud version, the new plugin that it uses to add worklog is called tempo, and even if Jira stopwatch is actually making this API call, it seems to do not get populated correctly, I cannot see the timelog in the ticket either.
However I realise it might not be an issue on your side but an issue on Jira's API.

Cheers

**Comment by cumminsjp** [comment]
I initially thought it wasn't working as well, but a co-worker informed me that it is severely delayed.  Sure enough, the hours that I submitted to JIRA last Friday via the JIRA Stopwatch appeared in my Tempo time sheet on Saturday.

**Comment by carstengehling** [comment]
So it's the integration between Jira and the Tempo plugin that has some issues.

**Comment by carstengehling** [comment]
@gallonmael can you confirm this?

**Comment by GallonMael** [comment]
Yes I can confirm, thank you both for this.
