### ISSUE TITLE
Don't build on Linux

### ISSUE THREAD

**Issue by joseeloren** [carstengehling/jirastopwatch#95]
Hi @carstengehling,

I read previous issues and Google the problem, but I didn't found the solution. I have macOS and Linux, so I can help you to get this working on every platform. But the problem is I get, always, on .resx files this:

```
Inner exception: AND data length expected 512, read 0
Parameter name: stream

```
Doesn't matter if I use xbuild or msbuild commands (I always do with .sln or .csproj). Also, I found on mono (that is an open source .NET framework that runs on Unix systems) this:

https://github.com/mono/mono/blob/master/mcs/class/System.Drawing/System.Drawing/Icon.cs#L862

You can see there what causes the exception.

Kind regards,

Jose Lorenzo.

**Comment by carstengehling** [comment]
I've tried a lot of different stuff, and I also cannot make it build on Mono anymore. I don't really have the time to dig deeper into this. But if you ever get succes, please let me know - even submit a pull request with the necessary changes.

**Comment by joseeloren** [comment]
Okay, I will do it 👍

**Comment by VladimirPal** [comment]
@joseeloren You can try another jira client - https://github.com/web-pal/chronos-timetracker it works on linux as well

**Comment by th-we** [comment]
@joseeloren I created related pull request #117. Though it makes the program compile, it does not start with that fix.

So I tried to identify remaining problems and for troubleshooting purposes commented out some window-related lines that caused problems. (See [this commit](https://github.com/th-we/jirastopwatch/commit/c4a5afe8d9e1e3f6d2761c982c86905be13a2a49), I created [a branch for fiddling](https://github.com/th-we/jirastopwatch/tree/linux-troubleshooting).) It now compiles and I can log in to Jira, fetch my issues, but the program will quickly fail because it does not find some DLLs.

It would be great if you could join me in finding out how to make those DLLs work and what to do with the sections I commented out.

**Comment by th-we** [comment]
I disabled some more code (and this time did it more properly by checking the platform instead of simply commenting out lines). Now it looks like I have a functional program in Linux. I added that to my pull request #117. I'll move the discussion there.
